# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c25cd1867b05294c65cfaf56f9d3589fc419781a04cebe9f2aea7a4252b759e98d972ed73d424f4f095ad77d6fef9589bf810dec167bf6b87992a171544d263d

test:
  secret_key_base: 903da2de45168b1f3e7edf5a2d4e602952255e49edc1a7bb9fe2bee65f7667fb3403cc8e5992cff3b7377bcb82b28f84061fe61ca07c3abfed1cf18528843910

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
